### PR TITLE
Pricing page

### PR DESCRIPTION
**Pull request by devkiran**

### CODE REVIEW

**Comment by devkiran** [comment]
@deepakprabhakara https://www.loom.com/share/d26e7c78faf0451cb376071c99b6ca97

**Review by niwsa — COMMENTED** [review]
Could be subjective, but I think we can allow some more breathing space by increasing the padding for lower screen sizes.
Screenshot 2022-12-06 at 9 14 18 PM

**Comment by devkiran** [comment]
> Could be subjective, but I think we can allow some more breathing space by increasing the padding for lower screen sizes. Screenshot 2022-12-06 at 9 14 18 PM

You mean to add padding (left and right) between table?

**Comment by niwsa** [comment]
You could adjust the body padding(left/right) or the width of the table so that there is some space between table and the outer browser window.

**Review by deepakprabhakara — APPROVED** [review]

**Pull request merged**
