### PR TITLE
Add Next.js and Supertokens example

### PR DESCRIPTION
**Pull request by nadilas**
Hey guys, here's a demo to combine Next.js with Supertokens.

### CODE REVIEW

**Comment by deepakprabhakara** [comment]
Thanks @nadilas, this looks amazing.

**Review by deepakprabhakara — APPROVED** [review]

**Comment by nadilas** [comment]
Also big thanks to @rishabhpoddar for the hot-fix 😉

**Comment by deepakprabhakara** [comment]
Thanks @rishabhpoddar :-)

**Comment by deepakprabhakara** [comment]
@nadilas Your feedback on the dev experience would be invaluable :). My email is deepak@boxyhq.com

**Comment by nadilas** [comment]
@deepakprabhakara one step ahead of me, I'll contact you with a few thoughts 👍

**Pull request merged**
