### PR TITLE
Guides improvements

### LINKED ISSUE #118: Guide: Add SAML SSO to AdonisJS app

### PR DESCRIPTION
**Pull request by devkiran**
Closes #118 #120 #121 #124

- [x] Laravel
- [x] Next.js
- [x] Express.js
- [x] AdonisJs
- [ ] Ruby on Rails @niwsa  
- [ ] Remix @niwsa

### CODE REVIEW

**Comment by niwsa** [comment]
The `Configuring SAML SSO` and `Log in with SAML SSO` guide content should apply for OIDC IdPs too,Right ?

**Comment by devkiran** [comment]
> The `Configuring SAML SSO` and `Log in with SAML SSO` guide content should be relevant for OIDC IdPs too,Right ?

The current content only focus on the SAML integration. Maybe we might need a different guide for ODIC configuration or add it to the existing content.

**Review by niwsa — CHANGES_REQUESTED** [review]

**Comment by devkiran** [comment]
@niwsa  Changes looks good to me.

**Review by niwsa — APPROVED** [review]

**Comment by devkiran** [comment]
@deepakprabhakara I've hidden the Ruby and Django links from the sidebar but kept the files as it is.

**Review by deepakprabhakara — APPROVED** [review]

**Comment by deepakprabhakara** [comment]
Great work @devkiran

**Pull request merged**
