### PR TITLE
add Product Hunt page

### PR DESCRIPTION
**Pull request by NathanTarbert**

### CODE REVIEW

**Comment by NathanTarbert** [comment]
I had a compromised branch. I will resolve the errors

**Review by deepakprabhakara — CHANGES_REQUESTED** [review]
Missing images, build fails

**Comment by NathanTarbert** [comment]
It should work now.

**Review by NathanTarbert — COMMENTED** [review]
Added the images.

**Review by deepakprabhakara — CHANGES_REQUESTED** [review]
Please rename the screenshots to something friendly, `Screenshot 2023-11-15 at 11.56.03 AM.png` is weird

**Comment by deepakprabhakara** [comment]
Customer image sizes are not the same.

**Comment by NathanTarbert** [comment]
Making the fix

**Review by deepakprabhakara — APPROVED** [review]

**Pull request merged**
