### PR TITLE
Update oss-friends.js - add hook0

### PR DESCRIPTION
**Pull request by FGRibreau**
Hi !

I discovered your OSS project and wondered if you could also add Hook0 inside it (of course we are also going to update our website accordingly). How can we join this community ? :)

### CODE REVIEW

**Comment by deepakprabhakara** [comment]
Hi @FGRibreau, please contact https://twitter.com/jobenjada who leads the initiative. :-)

**Comment by FGRibreau** [comment]
Thanks a lot! I just contacted him through Twitter DM, wait & see!

**Comment by NathanTarbert** [comment]
@FGRibreau, did you find who you were looking for and get an answer?

**Comment by FGRibreau** [comment]
@NathanTarbert yes! we are now referenced on formbricks [oss-friends page](https://formbricks.com/oss-friends), could you please also do the same 🙏

**Comment by deepakprabhakara** [comment]
@FGRibreau It's there now :)

**Pull request closed without merging**
